name: Hex

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.0' # Define the elixir version [required]
        otp-version: '25.0' # Define the OTP version [required]
        install-hex: true
    - name: Publish to Hex.pm
      run: |
        mix deps.get
        mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
